version: 2
jobs:
  build:
    docker:
      - image: circleci/clojure:lein-2.9.0-browsers-legacy

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "project.clj" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: lein deps

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}

  clj-test:
    docker:
      - image: circleci/clojure:lein-2.9.0-browsers-legacy
    steps:
      - run: lein test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test
